config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'posts#index'
  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    registrations: 'admins/registrations'
  }
  
  resources :posts, only: [:show] do 
    resources :reviews, only: [:index, :create, :destroy]
  end

  namespace :admin do
    resources :posts, only: [:new, :create, :index, :show, :edit, :update, :destroy]
    resources :genres, only: [:index, :create, :edit, :update, :destroy]
    resources :tags, only: [:index, :create, :edit, :update, :destroy]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :posts
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def create
    Genre.create(genre_params)
    @genres = Genre.all
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/views/admin/genres/_genres.html.erb
<% @genres.each do |genre| %>
  <div class="card mb-1">
    <div class="card-body">
      <p class="card-text"><%= genre.name %></p>
    </div>
  </div>
<% end %>

app/views/admin/genres/create.js.erb
$("textarea").val("");
$("input").val("");
$('#exampleModal').modal('hide')
$('.genres').html("<%= escape_javascript(render 'genres', genres: @genres) %>")

app/views/admin/genres/edit.html.erb
<h1>Admin::Genres#edit</h1>
<p>Find me in app/views/admin/genres/edit.html.erb</p>

app/views/admin/genres/index.html.erb
<div class="genre">
  <h2>Genre作成</h2>
  <div class="container">
    <div class="row">
      <div class="col-lg-5">
        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
          Genre作成
        </button>
        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Genre作成</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <%= form_with(model: @genre, url: admin_genres_path,method: :post) do |f| %>
                <div class="modal-body">
                  <div class="form-group">
                    <%= f.label :name, "ジャンル名" %>
                    <%= f.text_field :name,class:"form-control", placeholder: "食 温泉 海水浴 etc..." %>
                  </div>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">閉じる</button>
                  <%= f.submit "投稿する", class: "btn btn-outline-primary" %>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
      <div class="col-lg-5 genres">
        <%= render 'genres', genres: @genres %>
      </div>
    </div>
  </div>
</div>

  <%
=begin%>
 <div class="container-fluid">
    <div class="row">
      <div class="col-lg-12" style="text-align: center;">
        <div style="margin-bottom: 10px;">
          <%= form_with(model: @genre, url: admin_genres_path,
              method: :post, local: true) do |f| %>
          <%= f.label :ジャンル名 %>
          <%= f.text_field :name,class:"genre__form", placeholder: "食 温泉 自然 etc..." %>
          <%= f.submit '追加' ,class:"btn btn-outline-primary" %>
          <% end %>
        </div>
      </div>
      <table class="table">
        <thead class="thead-dark">
          <tr>
            <th scope="col"></th>
            <th scope="col">#</th>
            <th scope="col">ジャンル名</th>
            <th scope="col">link</th>
            <th scope="col">link</th>
          </tr>
        </thead>
        <tbody>
          <% @genres.each do |genre| %>
          <tr>
            <td></td>
            <td class=""><%= genre.id %></td>
            <td class=""><%= genre.name %></td>
            <td><%= link_to "編集する", edit_admin_genre_path(genre) ,class:"btns btn-outline-success" %></td>
            <td><%= link_to "削除する", admin_genre_path(genre) ,class:"btns btn-outline-danger" %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="col-lg-6"></div>
  </div>
 
<%
=end%>