config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'posts#index'
  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    registrations: 'admins/registrations'
  }
  
  resources :posts, only: [:show] do 
    resources :reviews, only: [:index, :create, :destroy]
  end

  namespace :admin do
    resources :posts, only: [:new, :create, :index, :show, :edit, :update, :destroy]
    resources :genres, only: [:index, :create, :edit, :update, :destroy]
    resources :tags, only: [:index, :create, :edit, :update, :destroy]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :post_tag_relations, dependent: :delete_all
  has_many :posts, through: :post_tag_relations
end

app/controllers/admin/tags_controller.rb
class Admin::TagsController < ApplicationController
  def index
    @tags = Tag.all
    @tag = Tag.new
  end

  def create
    @tag = Tag.new(tag_params)
    @tag.save
    redirect_to admin_tags_path, notice: 'tagの作成に成功しました。'
  end

  def edit
  end

  def update
  end

  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy
    redirect_to admin_tags_path
  end

  private

  def tag_params
    params.require(:tag).permit(:name)
  end

end

app/helpers/admin/tags_helper.rb
module Admin::TagsHelper
end

app/views/admin/tags/edit.html.erb
<h1>Admin::Tags#edit</h1>
<p>Find me in app/views/admin/tags/edit.html.erb</p>

app/views/admin/tags/index.html.erb
<div class="genre">
  <h2>Blog投稿</h2>
<div class="container-fluid">
  <div class="row">
    <div class="col-lg-12" style="text-align: center;">
      <div style="margin-bottom: 10px;">
        <%= form_with(model: @tag, url: admin_tags_path,
            method: :post, local: true) do |f| %>
        <%= f.label :タグ名 %>
        <%= f.text_field :name,class:"genre__form", placeholder: "◯◯市" %>
        <%= f.submit '追加' ,class:"btn btn-outline-primary" %>
        <% end %>
      </div>
    </div>
      <table class="table">
        <thead class="thead-dark">
          <tr>
            <th scope="col"></th>
            <th scope="col">#</th>
            <th scope="col">タグ名</th>
            <th scope="col">link</th>
            <th scope="col">link</th>
          </tr>
        </thead>
        <tbody>
          <% @tags.each do |tag| %>
          <tr>
            <td></td>
            <td class=""><%= tag.id %></td>
            <td class=""><%= tag.name %></td>
            <td><%= link_to "編集する", edit_admin_tag_path(tag) ,class:"btns btn-outline-success" %></td>
            <td><%= link_to "削除する", admin_tag_path(tag) , method: :delete,class:"btns btn-outline-danger" %></td>
          </tr>
          <% end %>
        </tbody>
      </table>

    </div>

    <div class="col-lg-6"></div>
  </div>
</div>