config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'posts#index'
  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    registrations: 'admins/registrations'
  }
  
  resources :posts, only: [:show] do 
    resources :reviews, only: [:index, :create, :destroy]
  end

  namespace :admin do
    resources :posts, only: [:new, :create, :index, :show, :edit, :update, :destroy]
    resources :genres, only: [:index, :create, :edit, :update, :destroy]
    resources :tags, only: [:index, :create, :edit, :update, :destroy]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  
  is_impressionable counter_cache: true
  mount_uploader :avatar, AvatarUploader
  has_many :post_tag_relations, dependent: :delete_all
  has_many :tags, through: :post_tag_relations
  belongs_to :genre
  has_many :reviews, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true
  validates :shop_name, presence: true

  def avg_score
    unless self.reviews.empty?
      reviews.average(:score).round(1).to_f
    else
      0.0
    end
  end

  def review_score_percentage
    unless self.reviews.empty?
      reviews.average(:score).round(1).to_f*100/5
    else
      0.0
    end
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to admin_posts_path(@post), notice: '投稿に成功しました。'
    else
      render :new
   end
  end

  def index
    @posts = params[:tag_id].present? ? Tag.find(params[:tag_id]).posts : Post.all
    @posts = @posts.page(params[:page]).per(10).order(created_at: :desc)
    @genres = Genre.all
    # urlにcategory_id(params)がある場合
    if params[:genre_id]
      # Categoryのデータベースのテーブルから一致するidを取得
      @genre = Genre.find(params[:genre_id])
      # category_idと紐づく投稿を取得
      @posts = @genre.posts.page(params[:page]).per(10).order(created_at: :desc)
    else
      # 投稿すべてを取得
      @posts = @posts.page(params[:page]).per(10).order(created_at: :desc)
    end
  end

  def show
    @posts = Post.all.order(created_at: :desc)
    @post = Post.find(params[:id])
    @genres = Genre.all
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.update(post_params)
    redirect_to admin_post_path
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to admin_posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :avatar, :body, :shop_name, :address, :url, :business_hours, :genre_id, tag_ids: [])
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:show]
  def index
    @post = Post.count
    @posts = params[:tag_id].present? ? Tag.find(params[:tag_id]).posts : Post.all
    @posts = @posts.page(params[:page]).per(10).order(created_at: :desc)
    @genres = Genre.all
    @rank_posts = Post.order(impressions_count: 'DESC')
    # urlにcategory_id(params)がある場合
    if params[:genre_id]
      # Categoryのデータベースのテーブルから一致するidを取得
      @genre = Genre.find(params[:genre_id])
      # category_idと紐づく投稿を取得
      @posts = @genre.posts.page(params[:page]).per(10).order(created_at: :desc)
    else
      # 投稿すべてを取得
      @posts = @posts.page(params[:page]).per(10).order(created_at: :desc)
    end
  end

  def show
    @posts = Post.all.order(created_at: :desc)
    @post = Post.find(params[:id])
    impressionist(@post, nil, unique: [:ip_address])
    @genres = Genre.all
    @review = Review.new
  end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admin/posts/_form.html.erb
  <%= form_with(url: admin_posts_path, model: @post, local: true) do |f| %>

  <% if @post.errors.any? %>
  <div class="posts-error">
    <h3><%= @post.errors.count %>eroor</h3>
    <ul>
      <% @post.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
    <% end %>
  

  <div class="row" style="margin: 10px;">
    <div class="col-lg-6 admin-posts-new__title">
      <p><%= f.label :title, 'タイトル　' %><span>必須</span></p>
    </div>
    <div class="col-lg-6">
      <%= f.text_field :title, class: "admin-posts-new__form", placeholder: "#1 title" %>
    </div>
  </div>

  <div class="row" style="margin: 10px;">
    <div class="col-lg-12 admin-posts-new__title">
      <%= f.file_field :avatar %>
    </div>
    <div class="col-lg-12">
      <img id="preview" class="preview" style="margin-left: 15%">
    </div>
  </div>
  <div class="row" style="margin: 10px;">
    <div class="col-lg-6 admin-posts-new__title">
      <p><%= f.label :body, '本文　' %><span>必須</span></p>
    </div>
    <div class="col-lg-6">
      <%= f.text_area :body, class: "admin-posts-new__forms" , placeholder: "◯◯がオススメです。"%>
    </div>
  </div>

  <div class="row" style="margin: 10px;">
    <div class="col-lg-6 admin-posts-new__title">
      <p><%= f.label :shop_name, 'Shop_Name　' %><span>必須</span></p>
    </div>
    <div class="col-lg-6">
      <%= f.text_field :shop_name, class: "admin-posts-new__form", placeholder: "◯◯Cafe" %>
    </div>
  </div>

  <div class="row" style="margin: 10px;">
    <div class="col-lg-6 admin-posts-new__title">
      <p><%= f.label :business_hours, '営業時間' %></p>
    </div>
    <div class="col-lg-6">
      <%= f.text_field :business_hours, class: "admin-posts-new__form" , placeholder: "◯◯〜◯◯" %>
    </div>
  </div>

  <div class="row" style="margin: 10px;">
    <div class="col-lg-6 admin-posts-new__title">
      <p><%= f.label :address, '住所' %></p>
    </div>
    <div class="col-lg-6">
      <%= f.text_field :address, class: "admin-posts-new__form" , placeholder: "◯◯市" %>
    </div>
  </div>

  <div class="row" style="margin: 10px;">
    <div class="col-lg-6 admin-posts-new__title">
      <p><%= f.label :url, 'HP_URL' %></p>
    </div>
    <div class="col-lg-6">
      <%= f.text_field :url, class: "admin-posts-new__form" , placeholder: "https://~" %>
    </div>
  </div>

  <div class="row" style="margin: 10px;">
    <div class="col-lg-6 admin-posts-new__title">
      <p>ジャンル　</p>
    </div>
    <div class="col-lg-6 genre-form">
      <%= f.collection_select :genre_id, Genre.all,
        :id, :name, include_blank: "-- 選択してください --" , class: "admin-posts-new__form" %>
    </div>
  </div>


  <div class="row" style="margin: 10px;">
    <div class="col-lg-6 admin-posts-new__title">
      <p>タグ</p>
    </div>
    <div class="col-lg-6">
      <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| %>
          <%= tag.label class: 'form-check-label' do %>
            <div><%= tag.check_box class: 'form-check-input' %></div>
            <%= tag.text %>
          <% end %>
      <% end %>
    </div>
  </div>
  <div>
    <%= f.submit "新規登録", class:"btn btn-outline-primary" %>
  </div>

  <% end %>
  <div style="margin: 10px 0px 50px 0px">
    <%= link_to "投稿一覧",admin_posts_path %>
  </div>

app/views/admin/posts/_side.html.erb
<div class="sidebar">
  <p>
    <span style="font-size: 13px;">【 Awaji_Place Blog 】</span><br>
    どうも！管理人のRyoです。この度私の出身地である淡路島の魅力をもっと多くの人に伝えたいと思いこのサイトを作りました。淡路島にあるナイスなSpotを中心に紹介しますが、兵庫県全体を紹介できたらなと思っています。よろしくお願いします!😄<br>
    by Ryo
  </p>

  <ul>
    <i class="fab fa-twitter"></i>
    <i class="fab fa-instagram-square"></i>
    <i class="fab fa-facebook"></i>
  </ul><br>
  <% if admin_signed_in? %>
    <div class="sidebar__link"><%= link_to "_ HOME", admin_posts_path %></div>
    <div class="sidebar__link"><%= link_to "_ BLOG投稿", new_admin_post_path %></div>
    <div class="sidebar__link"><%= link_to "_ GENRE作成", admin_genres_path %></div>
    <div class="sidebar__link"><%= link_to "_ TAG作成", admin_tags_path %></div>
    <div class="sidebar__link"><%= link_to "_ LAG_OUT", destroy_admin_session_path, method: :delete %></div>
    <div class="sidebar__link"><a href="" style="">_ NEWS</a></div>
    <div class="sidebar__link"><a href="" style="">_ プロフィールを見る</a></div><br>
  <% end %>

  <%
=begin%>
 <div class="sidebar__link">
    <form id="form1" action="自分のサイトURL" method="get">
    <input id="sbox1" id="s" name="s" type="text" placeholder="キーワードを入力" />
    <input id="sbtn1" class="form-btn pushright" type="submit" value="検索" /></form>
  </div> 
<%
=end%>
  <div class="sidebar__link">> 画像一覧</div>
  <div class="sidebar-image">
    <% @posts.each do |post| %>
    <div class="sidebar-image__contant">
      <!-- 4つごとに折り返し-->
      <%= link_to admin_post_path(post) do %>
        <% if post.avatar? %>
          <%= image_tag post.avatar_url, class:"sidebar-image__img" %>
        <% else %>
          <%= image_tag 'no_image.JPG', class: 'sidebar-image__img' %>
        <% end %>
      <% end %>
    </div>
    <% end %>
  </div>
  <div class="sidebar__contant">
    タグで検索
    <%= form_tag admin_posts_path, method: :get, class: 'posts__searchForm',style: 'margin-bottom: 5px;' do %>
      <%= select_tag :tag_id,
                  options_from_collection_for_select(Tag.all, :id, :name, params[:tag_id]),
                  {
                    prompt: 'タグで絞り込み',
                    class: 'posts__select',
                    onchange: 'submit(this.form);'
                  }
      %>
    <% end %>
  </div>
    <div class="sidebar__contant">
    <span>ジャンル一覧</span>
		<% @genres.each do |genre| %>
				<!-- クリックされたジャンルのgenre_idをparamsデータとして送信 -->
				<%= form_with url: admin_posts_path, method: :get, local: true do |f| %>
					<%= f.hidden_field :genre_id, :value => genre.id %>
					<span>・</span><%= f.submit genre.name,style:"background-color: white;
						border:0px solid black; cursor: pointer;" %>
				<% end %>
		<% end %>
  </div>
  <div class="sidebar__contant">
    最新の記事
    <% @posts.each do |post| %>
      <div class="sidebar__article">
      <!-- 4つごとに折り返し-->
      <%= link_to admin_post_path(post) do %>
        <p><%= post.title %></p>
        <p><%= post.created_at.strftime('%Y年/%m月/%d日') %></p>
      <% end %>
      <div style="margin-bottom: 10px;"></div>
      </div>
    <% end %>
  </div>
  <div class="footer">
    <%= render "posts/footer" %>
  </div>
</div>

app/views/admin/posts/edit.html.erb
<div class="admin-posts-new">
  <h2>Blogの編集</h2>
  <%= form_with(url: admin_post_path, model: @post, method: :patch, local: true) do |f| %>

  <% if @post.errors.any? %>
  <div class="posts-error">
    <h3><%= @post.errors.count %>eroor</h3>
    <ul>
      <% @post.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <div class="row" style="margin: 10px;">
    <div class="col-lg-6 admin-posts-new__title">
      <p>タイトル　<span>必須</span></p>
    </div>
    <div class="col-lg-6">
      <%= f.text_field :title, class: "admin-posts-new__form", placeholder: "#1 title" %>
    </div>
  </div>

  <div class="row" style="margin: 10px;">
    <div class="col-lg-12 admin-posts-new__title">
      <%= f.file_field :avatar %>
    </div>
    <div class="col-lg-12">
      <img id="preview" class="preview" style="margin-left: 15%">
    </div>
  </div>
  <div class="row" style="margin: 10px;">
    <div class="col-lg-6 admin-posts-new__title">
      <p>本文　<span>必須</span></p>
    </div>
    <div class="col-lg-6">
      <%= f.text_area :body, class: "admin-posts-new__forms" , placeholder: "◯◯がオススメです。"%>
    </div>
  </div>

  <div class="row" style="margin: 10px;">
    <div class="col-lg-6 admin-posts-new__title">
      <p>shop_name　<span>必須</span></p>
    </div>
    <div class="col-lg-6">
      <%= f.text_field :shop_name, class: "admin-posts-new__form", placeholder: "◯◯Cafe" %>
    </div>
  </div>

  <div class="row" style="margin: 10px;">
    <div class="col-lg-6 admin-posts-new__title">
      <p>営業時間</p>
    </div>
    <div class="col-lg-6">
      <%= f.text_field :business_hours, class: "admin-posts-new__form" , placeholder: "◯◯〜◯◯" %>
    </div>
  </div>

  <div class="row" style="margin: 10px;">
    <div class="col-lg-6 admin-posts-new__title">
      <p>住所</p>
    </div>
    <div class="col-lg-6">
      <%= f.text_field :address, class: "admin-posts-new__form" , placeholder: "◯◯市" %>
    </div>
  </div>

  <div class="row" style="margin: 10px;">
    <div class="col-lg-6 admin-posts-new__title">
      <p>HP_URL</p>
    </div>
    <div class="col-lg-6">
      <%= f.text_field :url, class: "admin-posts-new__form" , placeholder: "https://~"%>
    </div>
  </div>

  <div class="row" style="margin: 10px;">
    <div class="col-lg-6 admin-posts-new__title">
      <p>ジャンル　</p>
    </div>
    <div class="col-lg-6 genre-form">
      <%= f.collection_select :genre_id, Genre.all,
        :id, :name, include_blank: "-- 選択してください --" , class: "admin-posts-new__form" %>
    </div>
  </div>


  <div class="row" style="margin: 10px;">
    <div class="col-lg-6 admin-posts-new__title">
      <p>タグ</p>
    </div>
    <div class="col-lg-6">
      <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| %>
      <%= tag.label class: 'form-check-label' do %>
      <div><%= tag.check_box class: 'form-check-input' %></div>
      <%= tag.text %>
      <% end %>
      <% end %>
    </div>
  </div>


  <div>
    <%= f.submit "編集の完了", class:"btn btn-outline-primary" %>
  </div>

  <% end %>
  <div style="margin: 10px 0px 50px 0px">
    <%= link_to "投稿一覧",admin_posts_path %>
  </div>
</div>

app/views/admin/posts/index.html.erb
<div class="container-fluid ad-bg">
  <div class="row">
    <div class="col-lg-1"></div>
    <div class="col-lg-8">
      <div class="posts">
        <% @posts.each do |post| %>
        <div class="posts__content">
          <!-- 2つごとに折り返し-->
          <p class=""><%= post.title %></p>
          <span>
            <%= post.created_at.strftime('%Y/%m/%d') %>
          </span>
          <div class="genre-name">
            <%= post.genre.name %>
          </div>
          <%= link_to admin_post_path(post) do %>
          <% if post.avatar? %>
            <%= image_tag post.avatar_url, class:"posts__image" %>
          <% else %>
            <%= image_tag 'no_image.JPG', class: 'posts__image' %>
          <% end %>
          <% end %>
        </div>
        <% end %>
      </div>
      <%= paginate @posts %>
    </div>
    <div class="col-lg-2">
      <%= render "admin/posts/side", posts: @posts %>
    </div>
  </div>
</div>

app/views/admin/posts/new.html.erb
<div class="admin-posts-new">
  <h2>Blog投稿</h2>
  <%= render partial: 'form', locals: { post: @post } %>
</div>

app/views/admin/posts/show.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-lg-9">
      <div class="posts-show">
        <p class="posts-show__title"><%= @post.title %></p>
        <p class="posts-show__created"><%= @post.created_at.strftime('%Y年/%m月/%d日') %></p>
        <div class="posts-show__image">
          <% if @post.avatar? %>
            <%= image_tag @post.avatar_url, class:"product-show" %>
          <% else %>
            <%= image_tag 'no_image.JPG', class: 'product-show' %>
          <% end %>
        </div>
        <div class="posts-show__body"><%= @post.body %></div><br>
        <div class="posts-show__shop">
          <span><　</span><span><%= @post.shop_name %></span><span>　></span>
        </div>
        <p class="posts-show__created"><b>営業時間: </b><%= @post.business_hours %></p>
        <p class="posts-show__created"><b>住所: </b><%= @post.address %></p>
        <p class="posts-show__created"><b>URL: </b><%= text_url_to_link(h(@post.url)).html_safe %></p>
        <p class="posts-show__titles">Genre　</p><p class="badge badge-warning" style="padding: 5px;"><%= @post.genre.name %></p>
        <p></p>
        <p class="posts-show__titles">Tags　</p>
        <% @post.tags.each do |tag| %>
          <p class="badge badge-secondary" style="padding: 5px;">#<%= tag.name %></p>
        <% end %>
        </p>
        <% if admin_signed_in? %>
          <%= link_to edit_admin_post_path(params[:id]) do %>
            <span class="btn btn-outline-success" ,style="">編集</span>
          <% end %>
          <%= link_to "削除する",admin_post_path(@post), method: :delete, data: {confirm: "本当に削除してもよろしいですか？"},class: "btn btn-outline-danger" %>
        <% end %>
      </div>
    </div>
    <div class="col-lg-3">
      <%= render "admin/posts/side", posts: @posts %>
    </div>
  </div>
</div>